#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if ! command -v "pgrep" > /dev/null
then
    echo "It seems a necessary utility is missing, running doctor command"
    "$DIR"/jimClient doctor
    exit
fi

if ! pgrep -x "jimServer" > /dev/null
then
    "$DIR"/jimServer &
fi

"$DIR"/jimClient "$@"
