# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. 
on:
  push:
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # prepare environment
      - name: setup-go-bin
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      # Installs protoc etc.
      - name: install-requirements
        run: make install-requirements-linux-x86_64

      # Generates grpc implementation
      - name: protoc
        run: make protoc

      # Builds a release for linux and darwin
      - name: Build release
        run: make release

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
